### ISSUE TITLE
Sample Project using this and release on clojars?

### ISSUE THREAD

**Issue by rafaeldelboni** [lilactown/flex#11]
Hey first of all thanks for all your work on OSS for the cljs community I'm a Helix heavy user and is such a nice lib.

ATM I'm building a new side project and I'm evaluating tools to manage global state and searching for signal libraries I found this one.

I have two questions:

Do you have any sample project using this lib? I would like to see how is the ergonomics of it in a web/ui app doing async IOs and all that stuff :)

Since is doesn't have an official release, should I be careful with it's current state or big api changes?

Regards

**Comment by lilactown** [comment]
@rafaeldelboni there's some examples using flex and [flex-dom](https://github.com/lilactown/flex-dom), which is very experimental/not something I would encourage people to use. Flex itself is unlikely to change much; the integration with it and the DOM is still something I'm playing with. You could also build a React hook around it a la mobx.

I haven't bothered to put it on clojars yet and may at some point in the future, but for now I'd recommend using git deps.

**Comment by rafaeldelboni** [comment]
Thanks for your reply, I will do some evaluation on it. Do you have any recommendation on any library to manage global state on a react application today?

**Comment by rafaeldelboni** [comment]
Hey I've made a quick and dirt repo using a hook wrap around flex :)
https://github.com/rafaeldelboni/helix-flex

**Comment by lilactown** [comment]
Looks great!
